from datetime import datetime

from bson import ObjectId

from aquascope.webserver.data_access.db import Item


DUMMY_ITEMS = [
    Item({
        '_id': ObjectId('000000000000000000000000'),
        'filename': 'image_000.jpeg',
        'extension': '.jpeg',
        'group_id': 'processed',
        'empire': 'prokaryota',
        'kingdom': 'Bacteria',
        'phylum': 'Cyanobacteria',
        'class': 'Cyanophyceae',
        'order': 'Nostocales',
        'family': 'Nostocaceae',
        'genus': 'Anabaena',
        'species': 'sp',
        'dividing': False,
        'dead': False,
        'with_epiphytes': False,
        'broken': False,
        'colony': False,
        'eating': True,
        'multiple_species': False,
        'cropped': False,
        'male': None,
        'female': None,
        'juvenile': None,
        'adult': None,
        'with_eggs': None,
        'acquisition_time': datetime.fromtimestamp(1547974800.000),  # Human time: Sunday, 20 January 2019 10:00:00
        'image_width': 100,
        'image_height': 100
    }),
    Item({
        '_id': ObjectId('000000000000000000000001'),
        'filename': 'image_001.jpeg',
        'extension': '.jpeg',
        'group_id': 'processed',
        'empire': 'prokaryota',
        'kingdom': 'Bacteria',
        'phylum': 'Cyanobacteria',
        'class': 'Cyanophyceae',
        'order': 'Nostocales',
        'family': 'Nostocaceae',
        'genus': 'Anabaena',
        'species': 'sp',
        'dividing': False,
        'dead': False,
        'with_epiphytes': False,
        'broken': False,
        'colony': False,
        'eating': True,
        'multiple_species': False,
        'cropped': False,
        'male': None,
        'female': False,
        'juvenile': None,
        'adult': None,
        'with_eggs': None,
        'acquisition_time': datetime.fromtimestamp(1547960400.000),  # Human time: Sunday, 20 January 2019 06:00:00
        'image_width': 100,
        'image_height': 100
    }),
    Item({
        '_id': ObjectId('000000000000000000000002'),
        'filename': 'image_002.jpeg',
        'extension': '.jpeg',
        'group_id': 'processed',
        'empire': 'prokaryota',
        'kingdom': 'Bacteria',
        'phylum': 'Cyanobacteria',
        'class': 'Cyanophyceae',
        'order': 'Nostocales',
        'family': 'Nostocaceae',
        'genus': 'Anabaena',
        'species': 'sp',
        'dividing': False,
        'dead': False,
        'with_epiphytes': False,
        'broken': False,
        'colony': False,
        'eating': False,
        'multiple_species': False,
        'cropped': False,
        'male': None,
        'female': True,
        'juvenile': None,
        'adult': None,
        'with_eggs': None,
        'acquisition_time': datetime.fromtimestamp(1547110800.000),  # Human time: Thursday, 10 January 2019 10:00:00
        'image_width': 100,
        'image_height': 100
    }),
    Item({
        '_id': ObjectId('000000000000000000000003'),
        'filename': 'image_003.jpeg',
        'extension': '.jpeg',
        'group_id': 'processed',
        'empire': 'prokaryota',
        'kingdom': 'Bacteria',
        'phylum': 'Cyanobacteria',
        'class': 'Cyanophyceae',
        'order': 'Sphaeropleales',
        'family': 'Scenedesmaceae',
        'genus': 'Coelastrum',
        'species': 'reticulatum',
        'dividing': False,
        'dead': False,
        'with_epiphytes': False,
        'broken': False,
        'colony': False,
        'eating': None,
        'multiple_species': False,
        'cropped': False,
        'male': None,
        'female': None,
        'juvenile': None,
        'adult': None,
        'with_eggs': None,
        'acquisition_time': datetime.fromtimestamp(1546678800.000),  # Human time: Saturday, 5 January 2019 10:00:00
        'image_width': 100,
        'image_height': 100
    }),
    Item({
        '_id': ObjectId('000000000000000000000004'),
        'filename': 'image_004.jpeg',
        'extension': '.jpeg',
        'group_id': 'processed',
        'empire': 'prokaryota',
        'kingdom': 'Bacteria',
        'phylum': 'Cyanobacteria',
        'class': 'Cyanophyceae',
        'order': 'Sphaeropleales',
        'family': 'Scenedesmaceae',
        'genus': 'Coelastrum',
        'species': 'reticulatum',
        'dividing': False,
        'dead': False,
        'with_epiphytes': False,
        'broken': False,
        'colony': False,
        'eating': None,
        'multiple_species': False,
        'cropped': False,
        'male': None,
        'female': None,
        'juvenile': None,
        'adult': None,
        'with_eggs': None,
        'acquisition_time': datetime.fromtimestamp(1546333200.000),  # Human time: Saturday, 1 January 2019 10:00:00
        'image_width': 100,
        'image_height': 100
    })
]
